
import type { Metadata } from "next";
import "./globals.css";
import SessionWrapper from "@/components/SessionWrapper";
import { Provider } from "@/lib/reactQuery-provider";
import { Analytics } from '@vercel/analytics/next';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function NotiLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-neutral-800">
      <body className="pb-10">
        <SessionWrapper >
          <Provider>
            {children}
            <Analytics />
          </Provider>
        </SessionWrapper>
      </body>
    </html>
  );
}
